// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// DASHBOARD_INFO
export const FETCH_DASHBOARD_INFO_START = 'FETCH_DASHBOARD_INFO_START'; 
export const FETCH_DASHBOARD_INFO_SUCCESS = 'FETCH_DASHBOARD_INFO_SUCCESS'; 
export const FETCH_DASHBOARD_INFO_FAIL = 'FETCH_DASHBOARD_INFO_FAIL'; 

// ALARM
export const FETCH_ALARM_START = 'FETCH_ALARM_START'; 
export const FETCH_ALARM_SUCCESS = 'FETCH_ALARM_SUCCESS'; 
export const FETCH_ALARM_FAIL = 'FETCH_ALARM_FAIL'; 
