// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// SITE
export const FETCH_SITE_START = 'FETCH_SITE_START'; 
export const FETCH_SITE_SUCCESS = 'FETCH_SITE_SUCCESS'; 
export const FETCH_SITE_FAIL = 'FETCH_SITE_FAIL'; 

// ALARM
export const FETCH_ALARM_START = 'FETCH_ALARM_START'; 
export const FETCH_ALARM_SUCCESS = 'FETCH_ALARM_SUCCESS'; 
export const FETCH_ALARM_FAIL = 'FETCH_ALARM_FAIL'; 
